    name: Docker

    on:
      push:
        branches:
          - main
      pull_request:
        branches:
          - main

    jobs:
      build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
            token: ${{ secrets.GITHUB_TOKEN }}

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Log in to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Extract version
          id: vars
          run: echo "VERSION=$(cat VERSION | tr -d '[:space:]')" >> "$GITHUB_ENV"

        - name: Build and push
          uses: docker/build-push-action@v5
          with:
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:${{ env.VERSION }}
            platforms: linux/amd64,linux/arm64
            cache-from: type=gha
            cache-to: type=gha,mode=max
