    name: Docker

    on:
      push:
        branches:
          - main

    jobs:
      build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1

        - name: Log in to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Extract version
          id: vars
          run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

        - name: Build and push
          uses: docker/build-push-action@v2
          with:
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/your-repo-name:${{ env.VERSION }}